[package]
name = "py32f030_hal"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bare-metal = { version = "1.0.0" }
cast = "0.3"
cortex-m-rt = "0.7"
critical-section = { version = "1.1.2" }
embedded-hal = { version = "0.2", features = ["unproven"] }
nb = "1"
void = { version = "1.0", default-features = false }
panic-halt = "0.2.0"
panic-probe = { version = "0.3", features = ["print-defmt"] }

defmt = { version = "0.3.2", option = true }
defmt-rtt = { version = "0.4", option = true }
cortex-m = { version = "0.7.7", features = [
    "critical-section-single-core",
    "inline-asm",
] }
PY32f030xx-pac = "0.1.0"
num-traits = { version = "0.2", default-features = false }
heapless = "0.7"

embassy-hal-internal = { version = "0.1.0", features = [
    "cortex-m",
    "prio-bits-3",
] }


[profile.dev]
codegen-units = 1
opt-level = "z"
lto = "fat"
debug = true
overflow-checks = true
strip = false

[profile.release]
codegen-units = 1
opt-level = "z"
lto = true
debug = false
link-dead-code = false
overflow-checks = false
strip = true

[features]
default = ["extern_clk"]
extern_clk = []
inner_clk = []


[dev-dependencies]
panic-halt = "0.2"
usb-device = "0.2.7"
usbd-serial = "0.1.1"

[[example]]
name = "blinky"

[[example]]
name = "embassy_uart"
